apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  labels:
    app: pgadmin
data:
  PGADMIN_DEFAULT_EMAIL: admin@jussanjuan.com
  PGADMIN_DEFAULT_PASSWORD: password

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pgadmin-pv-volume
  labels:
    type: local
    app: pgadmin
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.5
    path: '/home/horse1/lab/sharenfs/pgadmin'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgadmin-pv-claim
  labels:
    app: pgadmin
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          resources:
           requests:
              memory: "256Mi"
              cpu: "250m"
           limits:
              memory: "512Mi"
              cpu: "500m"
          image: dpage/pgadmin4:5.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: pgadmin-config
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin
      volumes:
        - name: pgadmin
          persistentVolumeClaim:
            claimName: pgadmin-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: pgadmin
---

